### ISSUE TITLE
Braces color

### ISSUE THREAD

**Issue by SPAstef** [justinmk/vim-syntax-extra#12]
Braces get marked as errors if I enable parenthesis recognition in the "delimiters"

**Comment by justinmk** [comment]
> if I enable parenthesis recognition in the "delimiters"

What does that mean? Say exactly what you did, and give specific examples. And try with `vim -u DEFAULTS` .

**Comment by SPAstef** [comment]
I found the solution: I didn't put the standard syntax parser in the file, just this one. Now it all works perfectly. If you are interested, in the meanwhile I added the recognition of user defined types (it's a quite simple rule indeed). I was looking also for a way to make the double quotes and the angular parenthesis the same color of delimiters when they appear in strings (since they're not technically part of the string itself), but wasn't really successful
