### ISSUE TITLE
Syntax highlighting stops working 

### ISSUE THREAD

**Issue by seadb** [justinmk/vim-syntax-extra#4]
![capture](https://cloud.githubusercontent.com/assets/5834292/4670645/11d7b872-5579-11e4-8ff9-aa613a1c265d.PNG)

my syntax highlighting disappears after i have anything with brackets inside of a rule

**Comment by y2kbugger** [comment]
@bridsonc I'm curious, what what ended up fixing your problem, I am having a similar problem with a different syntax highlighting plugin.
