### ISSUE TITLE
Problem with `{` inside a bison action

### ISSUE THREAD

**Issue by pelegm** [justinmk/vim-syntax-extra#6]
The following code is not highlighted properly:

``` cpp
i_bexpr : iexpr i_boolop iexpr
        { $$ = new Bool<int,int>(Bool<int,int>::Args{$1,$3},
                                 Bool<int,int>::T_ops{$2}); }
        | i_bexpr i_boolop iexpr
        { std::cout << $1->args[0]->repr() << std::endl;
          $1->args.insert($1->args.end(), $3);
          $1->ops.insert($1->ops.end(), $2);
          $$ = $1; }
```

It looks like that:
![bison-vim](https://cloud.githubusercontent.com/assets/3422626/7584519/d0c978d0-f8a6-11e4-8268-95245e160d78.png)

Thanks for these syntax files!

**Comment by theKidOfArcrania** [comment]
This issue has been really annoying my ocd side... the issue should be fixed in my pull request. :)

**Comment by justinmk** [comment]
closed by https://github.com/justinmk/vim-syntax-extra/pull/10
