### ISSUE TITLE
cUserFunctionPointer does not highlight

### ISSUE THREAD

**Issue by nhooyr** [justinmk/vim-syntax-extra#8]
However if I run this command to match it again 

``` vim
syn match cUserFunctionPointer "(\s*\*\s*\h\w*\s*)\(\s\|\n\)*(" contains=cDelimiter,cOperator
```

It starts working perfectly. But now, if I do

``` vim
set ft=c
```

The highlighting disappears.

**Comment by justinmk** [comment]
Patch welcome :)

**Comment by nhooyr** [comment]
Going to close as it has been a long time and I'm not sure if this is relevant anymore.
